# Generated by Django 4.2.9 on 2024-03-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('MURO_MANAGER', 'Muro Manager'), ('BUSINESS_SUPERVISOR', 'Business Supervisor'), ('RELATIONSHIP_OFFICER', 'Relationship Officer'), ('LOAN_OFFICER', 'Loan Officer'), ('ACCOUNTANT', 'Accountant'), ('BRANCH_MANAGER', 'Branch Manager')], default='LOAN_OFFICER', max_length=20),
        ),
    ]
