# Generated by Django 4.2.7 on 2024-02-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0002_person_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='client_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
