# Generated by Django 4.2.7 on 2024-02-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0003_person_client_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='account_balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
