# Generated by Django 4.2.9 on 2024-03-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0004_alter_person_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=15),
        ),
    ]
