# Generated by Django 4.2.9 on 2024-03-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0005_alter_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='marital_status',
            field=models.CharField(default='S', max_length=15),
        ),
    ]
