# Generated by Django 4.2.9 on 2024-03-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0006_alter_person_marital_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Clients'},
        ),
    ]
