# Generated by Django 4.2.9 on 2024-08-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0008_alter_person_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
