# Generated by Django 5.0.1 on 2024-02-25 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0002_initial'),
        ('clientApp', '0001_initial'),
        ('loan', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by', to='users.profile'),
        ),
        migrations.AddField(
            model_name='loan',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
        ),
        migrations.AddField(
            model_name='loan',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientApp.person'),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantor', to='clientApp.person'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='loanimage',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loanproduct'),
        ),
        migrations.AddField(
            model_name='remarks',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='remarks',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
        migrations.AddField(
            model_name='loan',
            name='security_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.securitytype'),
        ),
    ]
