# Generated by Django 4.2.7 on 2024-02-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loan_disbursment_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='loan_documents/'),
        ),
    ]
