# Generated by Django 4.2.7 on 2024-02-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='deposited_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='deposit_made_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
