# Generated by Django 4.2.7 on 2024-02-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_deposit_deposited_at_loan_deposit_made_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='demanded_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
