# Generated by Django 4.2.7 on 2024-02-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_loan_demanded_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='interest',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
