# Generated by Django 4.2.7 on 2024-02-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanamortization',
            name='amount',
        ),
        migrations.AddField(
            model_name='loanamortization',
            name='ending_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanamortization',
            name='interest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanamortization',
            name='principal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
