# Generated by Django 4.2.7 on 2024-02-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_remove_loanamortization_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='account_interest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='installment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='unit_interest',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
