# Generated by Django 4.2.7 on 2024-03-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0014_remove_loan_document_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
