# Generated by Django 4.2.7 on 2024-03-05 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0015_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='ammortization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.loanamortization'),
        ),
    ]
