# Generated by Django 4.2.9 on 2024-03-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0017_penalty_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalty',
            name='name',
        ),
    ]
