# Generated by Django 4.2.9 on 2024-03-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0018_remove_penalty_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='previous_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
