# Generated by Django 4.2.9 on 2024-06-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0019_deposit_previous_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='guarantor_relationship',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='security_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='securitytype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
