# Generated by Django 4.2.9 on 2024-07-03 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0007_alter_person_options'),
        ('loan', '0026_remove_loan_guarantors_loan_guarantor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='guarantor',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='guarantor_relationship',
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guarantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantee', to='clientApp.person')),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientApp.person')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
            ],
        ),
    ]
