# Generated by Django 4.2.9 on 2024-07-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0007_alter_person_options'),
        ('loan', '0027_remove_loan_guarantor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guarantor',
            new_name='LoanGuarantor',
        ),
    ]
