# Generated by Django 4.2.9 on 2024-08-04 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0029_loanamortization_interest_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField()),
                ('payment_type', models.CharField(choices=[('PENALTY', 'PENALTY'), ('INTEREST', 'INTEREST'), ('PRINCIPAL', 'PRINCIPAL')], default='INTEREST', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ammortization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.loanamortization')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
            ],
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='ammortization',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='interest',
        ),
        migrations.DeleteModel(
            name='PenaltyPayments',
        ),
    ]
