# Generated by Django 4.2.9 on 2024-08-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0031_alter_deposit_deposit_alter_deposit_deposited_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='demanded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
