# Generated by Django 4.2.9 on 2024-08-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0032_alter_loan_demanded_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='client_loan_account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
