# Generated by Django 4.2.9 on 2024-08-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0034_systemparameters_remove_payments_loan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemparameters',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
