# Generated by Django 4.2.9 on 2024-08-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0035_systemparameters_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemparameters',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
