# Generated by Django 4.2.9 on 2024-08-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0037_delete_penalty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='deposit',
            new_name='amount_deposited',
        ),
    ]
