# Generated by Django 4.2.9 on 2024-08-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0039_remove_systemparameters_float_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='previous_balance',
        ),
    ]
