# Generated by Django 4.2.9 on 2024-08-20 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0040_remove_deposit_previous_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='balance_on_account_after_payments',
        ),
        migrations.AddField(
            model_name='payments',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.deposit'),
        ),
    ]
