# Generated by Django 4.2.9 on 2024-08-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0041_remove_deposit_balance_on_account_after_payments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanamortization',
            name='penalty_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanamortization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
