# Generated by Django 4.2.9 on 2024-08-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0043_loanimage_created_at_loanimage_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemparameters',
            options={'ordering': ['code'], 'verbose_name_plural': 'System Parameters'},
        ),
        migrations.RenameField(
            model_name='systemparameters',
            old_name='name',
            new_name='code',
        ),
    ]
