# Generated by Django 4.2.9 on 2024-11-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0045_alter_payments_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='loan_balance_after_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deposit',
            name='loan_balance_at_time_of_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
