# Generated by Django 4.2.9 on 2024-08-24 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0002_alter_account_code_alter_account_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='note',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_debit',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cash_flow_classification',
            field=models.CharField(choices=[('INVESTING_ACTIVITIES', 'Investing Activities'), ('FINANCING_ACTIVITIES', 'Financing Activities'), ('OPERATING_ACTIVITIES', 'Operating Activities')], default='OPERATING_ACTIVITIES', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='income_statement_classification',
            field=models.CharField(choices=[('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], default='REVENUE', max_length=255),
        ),
        migrations.CreateModel(
            name='JournalEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], default='DEBIT', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('account_balance_before_transaction', models.DecimalField(decimal_places=2, max_digits=20)),
                ('account_balance_after_transaction', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounting.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries_created_by', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounting.transaction')),
            ],
        ),
    ]
