# Generated by Django 4.2.9 on 2024-08-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.CharField(choices=[('CURRENT_ASSETS', 'Current Assets'), ('FIXED_ASSETS', 'Fixed Assets'), ('CURRENT_LIABILITIES', 'Current Liabilities'), ('LONG_TERM_LIABILITIES', 'Long Term Liabilities'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], default='CURRENT_ASSETS', max_length=255),
        ),
    ]
