# Generated by Django 4.2.9 on 2024-08-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_account_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='parent',
        ),
    ]
