# Generated by Django 4.2.9 on 2024-08-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_remove_account_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='description',
            new_name='narration',
        ),
        migrations.AddField(
            model_name='journalentries',
            name='narration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
