# Generated by Django 4.2.9 on 2024-08-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_rename_description_transaction_narration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentries',
            name='created_by',
        ),
    ]
